package com.backbase.assignment

import com.backbase.assignment.ui.util.INetworkCall

class FakeNetworkCall : INetworkCall {
    var isFail = false
    override var onError = { _: Exception -> }
    override suspend fun getJsonString(uri: String): String {
        if (isFail) return ""
        return when {
            uri.contains("now_playing") -> getNowPlayingMovieJsonString()
            uri.contains("popular") -> getPopularMoviesJsonString()
            uri.contains("464052") -> getMovieDetailsJsonString()
            else -> ""
        }
    }

    private fun getNowPlayingMovieJsonString() =
        "{\"dates\":{\"maximum\":\"2021-08-09\",\"minimum\":\"2021-06-22\"},\"page\":1,\"results\":[{\"adult\":false,\"backdrop_path\":\"/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg\",\"genre_ids\":[28,12,35,878],\"id\":436969,\"original_language\":\"en\",\"original_title\":\"The Suicide Squad\",\"overview\":\"Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.\",\"popularity\":8169.739,\"poster_path\":\"/464N3J1i6L5SsazPmX9m3q1GiZ3.jpg\",\"release_date\":\"2021-07-28\",\"title\":\"The Suicide Squad\",\"video\":false,\"vote_average\":8.1,\"vote_count\":1572},{\"adult\":false,\"backdrop_path\":\"/bwBmo4I3fqMsVvVtamyVJHXGnLF.jpg\",\"genre_ids\":[12,14,35,28],\"id\":451048,\"original_language\":\"en\",\"original_title\":\"Jungle Cruise\",\"overview\":\"Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.\",\"popularity\":3581.187,\"poster_path\":\"/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg\",\"release_date\":\"2021-07-28\",\"title\":\"Jungle Cruise\",\"video\":false,\"vote_average\":8,\"vote_count\":1400}],\"total_pages\":54,\"total_results\":1068}"

    private fun getPopularMoviesJsonString() =
        "{\"page\":1,\"results\":[{\"adult\":false,\"backdrop_path\":\"/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg\",\"genre_ids\":[28,12,35,878],\"id\":436969,\"original_language\":\"en\",\"original_title\":\"The Suicide Squad\",\"overview\":\"Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.\",\"popularity\":8169.739,\"poster_path\":\"/464N3J1i6L5SsazPmX9m3q1GiZ3.jpg\",\"release_date\":\"2021-07-28\",\"title\":\"The Suicide Squad\",\"video\":false,\"vote_average\":8.1,\"vote_count\":1572},{\"adult\":false,\"backdrop_path\":\"/bwBmo4I3fqMsVvVtamyVJHXGnLF.jpg\",\"genre_ids\":[12,14,35,28],\"id\":451048,\"original_language\":\"en\",\"original_title\":\"Jungle Cruise\",\"overview\":\"Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.\",\"popularity\":3581.187,\"poster_path\":\"/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg\",\"release_date\":\"2021-07-28\",\"title\":\"Jungle Cruise\",\"video\":false,\"vote_average\":8,\"vote_count\":1400},{\"adult\":false,\"backdrop_path\":\"/dq18nCTTLpy9PmtzZI6Y2yAgdw5.jpg\",\"genre_ids\":[28,12,53,878],\"id\":497698,\"original_language\":\"en\",\"original_title\":\"Black Widow\",\"overview\":\"Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.\",\"popularity\":4128.319,\"poster_path\":\"/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg\",\"release_date\":\"2021-07-07\",\"title\":\"Black Widow\",\"video\":false,\"vote_average\":7.9,\"vote_count\":4006}],\"total_pages\":500,\"total_results\":10000}"

    private fun getMovieDetailsJsonString() =
        "{\"adult\":false,\"backdrop_path\":\"/dq18nCTTLpy9PmtzZI6Y2yAgdw5.jpg\",\"belongs_to_collection\":null,\"budget\":200000000,\"genres\":[{\"id\":28,\"name\":\"Action\"},{\"id\":12,\"name\":\"Adventure\"},{\"id\":53,\"name\":\"Thriller\"},{\"id\":878,\"name\":\"Science Fiction\"}],\"homepage\":\"https://www.marvel.com/movies/black-widow\",\"id\":497698,\"imdb_id\":\"tt3480822\",\"original_language\":\"en\",\"original_title\":\"Black Widow\",\"overview\":\"Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.\",\"popularity\":4128.319,\"poster_path\":\"/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg\",\"production_companies\":[{\"id\":420,\"logo_path\":\"/hUzeosd33nzE5MCNsZxCGEKTXaQ.png\",\"name\":\"Marvel Studios\",\"origin_country\":\"US\"}],\"production_countries\":[{\"iso_3166_1\":\"US\",\"name\":\"United States of America\"}],\"release_date\":\"2021-07-07\",\"revenue\":359758784,\"runtime\":134,\"spoken_languages\":[{\"english_name\":\"English\",\"iso_639_1\":\"en\",\"name\":\"English\"},{\"english_name\":\"Russian\",\"iso_639_1\":\"ru\",\"name\":\"Pусский\"}],\"status\":\"Released\",\"tagline\":\"Her world. Her secrets. Her legacy.\",\"title\":\"Black Widow\",\"video\":false,\"vote_average\":7.9,\"vote_count\":4008}"
}